INSERT INTO Rooms (floorNum, roomNo, roomType, qLevel, beds, smoking, rate, capacity, description, image) VALUES
(1, 101, 'Single', 'Economic', 1, FALSE, 100, 2,"","src/main/java/com/GoldenOpportunity/Images/Rooms/roomStandard.jpg"),
(1, 102, 'Double', 'Economic', 2, FALSE, 125, 4,"","src/main/java/com/GoldenOpportunity/Images/Rooms/roomStandard.jpg"),
(1, 103, 'Double', 'Economic', 2, FALSE, 125, 4,"","src/main/java/com/GoldenOpportunity/Images/Rooms/roomStandard.jpg"),
(1, 104, 'Single', 'Business', 1, FALSE, 120, 2,"","src/main/java/com/GoldenOpportunity/Images/Rooms/roomStandard.jpg"),
(1, 105, 'Family', 'Comfort', 3, FALSE, 150, 6,"","src/main/java/com/GoldenOpportunity/Images/Rooms/roomStandard.jpg"),
(2, 201, 'Suite', 'Economic', 2, TRUE, 120,4,"","src/main/java/com/GoldenOpportunity/Images/Rooms/roomSuite.jpg"),
(2, 202, 'Deluxe', 'Business', 1, TRUE, 120,2,"","src/main/java/com/GoldenOpportunity/Images/Rooms/roomDeluxe.png"),
(2, 203, 'Suite', 'Comfort', 3, TRUE, 150,6,"","src/main/java/com/GoldenOpportunity/Images/Rooms/roomSuite.jpg"),
(2, 204, 'Suite', 'Comfort', 4, TRUE, 165,8,"","src/main/java/com/GoldenOpportunity/Images/Rooms/roomSuite.jpg"),
(2, 205, 'Deluxe', 'Executive', 2, TRUE, 180,4,"","src/main/java/com/GoldenOpportunity/Images/Rooms/roomDeluxe.png"),
(3, 301, 'Standard', 'Executive', 1, TRUE, 170,2,"","src/main/java/com/GoldenOpportunity/Images/Rooms/roomStandard.jpg"),
(3, 302, 'Standard', 'Economic', 1, TRUE, 160,2,"","src/main/java/com/GoldenOpportunity/Images/Rooms/roomStandard.jpg"),
(3, 303, 'Deluxe', 'Executive', 1, TRUE, 180,2,"","src/main/java/com/GoldenOpportunity/Images/Rooms/roomDeluxe.png"),
(3, 304, 'Deluxe', 'Business', 2, TRUE, 190,4,"","src/main/java/com/GoldenOpportunity/Images/Rooms/roomDeluxe.png"),
(3, 305, 'Deluxe', 'Executive', 2, TRUE, 200,4,"","src/main/java/com/GoldenOpportunity/Images/Rooms/roomDeluxe.png");